apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-database
spec:
  type: {{ .Values.database.serviceType }}
  ports:
    - port: {{ .Values.database.servicePort }}
  selector:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
