# myapp/templates/frontend-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.name" . }}-frontend
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.servicePort }}
  selector:
    app: {{ include "myapp.name" . }}-frontend
