# myapp/values.yaml

frontend:
  image:
    repository: "myapp/frontend"
    tag: "latest"
  servicePort: 8080
  replicas: 3

backend:
  image:
    repository: "myapp/backend"
    tag: "latest"
  servicePort: 8081
  replicas: 2

database:
  image:
    repository: "myapp/database"
    tag: "latest"
  servicePort: 5432
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
