frontend:
  image: "frontend-image:v1"
  replicas: 3
  serviceType: "ClusterIP"
  servicePort: 80

backend:
  image: "backend-image:v1"
  replicas: 3
  serviceType: "ClusterIP"
  servicePort: 8080

database:
  image: "database-image:v1"
  replicas: 1
  serviceType: "ClusterIP"
  servicePort: 5432
  persistence:
    enabled: true
    size: "10Gi"
